+ funcs: ansible: unansenv: also allow to wipe out from path, etc
we recently added ansenv() which sets up ansible venv first in path and
sets some ansible environment variables.  often we're using an edit
terminal to edit things besides ansible, and we want to be able to
switch between "ansible editing mode" and "non-ansible editing mode" at
will within this terminal, without needing an ansible editing terminal
and a non-ansible editing terminal

diff --git a/func.d/ansible b/func.d/ansible
--- a/func.d/ansible
+++ b/func.d/ansible
@@ -28,3 +28,22 @@ ansenv ()
 		PATH=$newpath
 	fi
 }
+
+ansunenv ()
+{
+	local -a oldpath
+
+	unset ANSIBLE_REMOTE_USER
+	unset ANSIBLE_VAULT_PASSWORD_FILE
+	unset ANSVAULT_PGPFILE
+
+	if [[ $PATH =~ [[:space:]] ]]; then
+		echo "path cannot contain whitespace" >&2; false; return; fi
+
+	oldpath=(${PATH//:/$'\x20'})
+	for ((i = 0; i < ${#oldpath[@]}; i++)); do
+		if [[ ${oldpath[i]} =~ /setup/venv/bin ]]; then
+			unset "oldpath[$i]"; break; fi; done
+
+	PATH=$(IFS=:; echo "${oldpath[*]}")
+}
