= func: taskw: tasklast: fix accidental expanded whitespace
this happened because turned off :list in vim and misleadingly thought
they were tabs already

diff --git a/func.d/taskw b/func.d/taskw
--- a/func.d/taskw
+++ b/func.d/taskw
@@ -302,31 +302,31 @@ timevals ()
 
 tasklast ()
 {
-        local curfql interval
+	local curfql interval
 
-        fql_of_interval ()
-        {
-                printf $(
-                        timew export \
-                        | jq -r ".[] | select(.id == ${1:?}) | .tags[]" \
-                        | grep -v -e ^+ -e /$ \
-                        | paste -sd,
-                )
-        }
+	fql_of_interval ()
+	{
+		printf $(
+			timew export \
+			| jq -r ".[] | select(.id == ${1:?}) | .tags[]" \
+			| grep -v -e ^+ -e /$ \
+			| paste -sd,
+		)
+	}
 
-        curfql=$(fql_of_interval 1)
-        interval=2
+	curfql=$(fql_of_interval 1)
+	interval=2
 
-        # last interval different than the current one
-        while true; do
-                candidate=$(fql_of_interval $interval)
-                if [[ $candidate == $curfql ]]
-                then let interval++; continue
-                elif [[ $candidate ]]
-                then break # found it
-                else echo "cannot find last fql" >&2; false; return
-                fi
-        done
+	# last interval different than the current one
+	while true; do
+		candidate=$(fql_of_interval $interval)
+		if [[ $candidate == $curfql ]]
+		then let interval++; continue
+		elif [[ $candidate ]]
+		then break # found it
+		else echo "cannot find last fql" >&2; false; return
+		fi
+	done
 
-        echo timew continue @$interval
+	echo timew continue @$interval
 }
