+ func: taskcur: like taskl but always uses the current task
instead of taking an arg that gets resolved usin 'taskid' this one will
just always use the currently active task, but will abort if that task
is not actually started

diff --git a/func.d/taskw b/func.d/taskw
--- a/func.d/taskw
+++ b/func.d/taskw
@@ -22,6 +22,19 @@ taskl ()
 	task $(taskid $taskid) "$@"
 }
 
+taskcur ()
+{
+	local tasknow=($(tasknow))
+	local status=${tasknow[1]}
+	local name=${tasknow[0]}
+
+	if [[ $status != 'started' ]]; then
+		echo "current task $name not engaged, aborting" >&2
+		false; return; fi
+
+	task $(taskid $name) "$@"
+}
+
 # for taskadd
 #
 taskaddl () { TASKADD="$*"; } # additional args (such as tags)
